### ISSUE TITLE
Dragging a box that is a child of a box drags both boxes

### ISSUE THREAD

**Issue by jezell** [hyper-designed/box_transform#10]
If you make a TransformableBox a child of another TransformableBox, dragging the child will result in dragging both the parent and the child rather than just the child.

**Comment by SaadArdati** [comment]
This issue is on our radar. Will let you know when it is resolved. 🙏

**Comment by SaadArdati** [comment]
If you wish to resolve this issue immediately for your use case, you should set TransformableBoxes as siblings instead of nesting them.

We will be exploring the usage of GestureDetectors soon to resolve this issue soon regardless.

Here's a minimal reproducible example:
https://gist.github.com/SaadArdati/222af3bab30fc2b4d30610a9f21a6a4f

**Comment by SaadArdati** [comment]
Fixed in [c9afe22](https://github.com/hyper-designed/box_transform/pull/15/commits/c9afe229b5d2a41030e32abea71c821547a468c2)

PR is #15
