### ISSUE TITLE
Impossible to disable content flipping?

### ISSUE THREAD

**Issue by jezell** [hyper-designed/box_transform#9]
Love the library, but can't seem to get these working:

```
allowContentFlipping: false,
flipWhileResizing: false,
```

I want to disable the resize past zero / flipping but they don't appear to have any effect, whether they are set on the TransformableBoxController or the TransformableBox.

**Comment by SaadArdati** [comment]
Did you mean you want the resize to stop overflowing to the opposite side when it hits a clamped box? If so, this is the feature i've been working on implementing the past two days.

It's a little more difficult to solve due to the different resize modes. If you want to use a basic working freeform variation, you can check out my branch `resize_overflow_mechanism`.

If you instead meant something else, please show us a small video or some better way of detailing your expected behavior and your result.

**Comment by SaadArdati** [comment]
We published an update that overhauls our resizing mechanism. Please test it out for us and let us know if we've addressed your issues. 🙏
